route:
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname', 'cluster', 'service']
  receiver: telegram

templates:
  - "/etc/alertmanager/templates/*.tmpl"

receivers:
  - name: telegram
    telegram_configs:
      - api_url: https://api.telegram.org
        parse_mode: "HTML"
        message: '{{ template "telegram.default" .}}'
        chat_id: xxxxxx                                 # your telegram user id
        bot_token: xxxxxxxx:xxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxx   # your telegram bot token
